// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeC-KAih8kqRCLurnyKeh3ff53EAegs4g',
    appId: '1:1051307429283:web:007600b9f3952ae51ede16',
    messagingSenderId: '1051307429283',
    projectId: 'chatapplication-dec05',
    authDomain: 'chatapplication-dec05.firebaseapp.com',
    storageBucket: 'chatapplication-dec05.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQKyaW6mIgyokig5VUBzeO1psPfBlt16k',
    appId: '1:1051307429283:android:f54fa041cb7be9751ede16',
    messagingSenderId: '1051307429283',
    projectId: 'chatapplication-dec05',
    storageBucket: 'chatapplication-dec05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf6KSt52_r-AjTpLTw8tRwz6QjY57WZ3Y',
    appId: '1:1051307429283:ios:8b9fb399b9049dad1ede16',
    messagingSenderId: '1051307429283',
    projectId: 'chatapplication-dec05',
    storageBucket: 'chatapplication-dec05.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf6KSt52_r-AjTpLTw8tRwz6QjY57WZ3Y',
    appId: '1:1051307429283:ios:8b9fb399b9049dad1ede16',
    messagingSenderId: '1051307429283',
    projectId: 'chatapplication-dec05',
    storageBucket: 'chatapplication-dec05.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeC-KAih8kqRCLurnyKeh3ff53EAegs4g',
    appId: '1:1051307429283:web:7b39c30776f931ac1ede16',
    messagingSenderId: '1051307429283',
    projectId: 'chatapplication-dec05',
    authDomain: 'chatapplication-dec05.firebaseapp.com',
    storageBucket: 'chatapplication-dec05.appspot.com',
  );
}
